from setuptools import setup, find_packages
setup(
    name = "visularity",
    version = "0.1.0",
    packages = find_packages(),

    install_requires = ['gensim>=0.8', 'scipy>=0.10.1'],

    author = "William John Bert",
    author_email = "william.bert@gmail.com",
    description = "Clustering visualization for similarity indexes generated by gensim.",
    license = "PSF",
    keywords = "gensim semantic similarity cluster visualization",
)
